### ISSUE TITLE
[6.x] [Dev] Short-term roadmap

### ISSUE THREAD

**Issue by DDuarte** [TrinityCore/TrinityCore#13553]
Place to organize done and future work on the `6.x` branch.
Note to devs: please edit this post as required.

TODO
=====

- [x] Auth (Win, Win64, Mac, Mac64)
- [x] Login & logout ingame
- [x] SMSG_UPDATE_OBJECT
- [x] Char_enum
- [x] Extractors 6.x (maps/vmaps/dbcs) (enUS/enGB at least)
- [x] Movement
    - [x] Player client movement (assigned to @streetrat)
    - [x] Player server movement (assigned to @Intel)
    - [x] Monster movement
    - [ ] Update misc movement packets (Missing opcodes)
- [x] Spell casting
    - [x] CMSG_CAST_SPELL
    - [x] SMSG_SPELL_START
    - [x] SMSG_SPELL_GO
    - [x] Store spell effects in a `std::vector` instead of hardcoded\[MAX_SPELL_EFFECTS\] (assigned to @streetrat)
- [x] Chat
    - [x] Addons
    - [x] Whisper
    - [x] Emotes (anims)
- [x] `playercreateinfo_*` (assigned to @DDuarte)
- [x] DBC & DB2 structs (ref #13552)
    - [x] Item-sparse (assigned to @Intel)
- [x] Cherry-pick commits from the 3.3.5 branch to 6.x (assigned to @DDuarte) (Ongoing)
- [x] Gossips (assigned to @Intel)
- [ ] Groups (invite, kick, set assistant, make raid, etc)
- [x] Achievements
- [ ] Guilds
- [x] Implement new race/class pairs (probably playercreateinfo?)
- [x] Channels (assigned to @joschiwald)
    - [x] Moderation
    - [ ] SMSG_CHANNEL_NOTIFY

**Comment by n4ndo** [comment]
@msoky  i think phases is stoped right now.

**Comment by Killyana** [comment]
I think this can be added to the todo list: https://github.com/TrinityCore/TrinityCore/issues/14018

**Comment by DDuarte** [comment]
Bare bare basics have been done.

**Comment by scorched-wow** [comment]
Also CMSG_CONNECT_TO_FAILED is important now haha that's wont let you enter in game.

**Comment by DDuarte** [comment]
? In-game login has been possible for a while...

**Comment by scorched-wow** [comment]
Received not handled opcode [CMSG_CONNECT_TO_FAILED 0x0135 (309)] from [Player: <none> (Account: 1)]
(Create Level 1 Character then entering the game.. loading screen about 90% then stop.) 
I'll have a look tomorrow as going sleep now.

**Comment by dr3adx** [comment]
Please fix groups and guilds.

**Comment by msoky** [comment]
@scorched-wow i can enter in game for a 2 months ago...

**Comment by scorched-wow** [comment]
What about today? can you enter? did you pull update till today?

http://i57.tinypic.com/2vl36ns.png
http://i60.tinypic.com/2gwrxy1.png (for long time waiting).

**Comment by Exodius** [comment]
I think that Archaeology is worth the mention? Backporting to 4.3.4 included after it gets completed for 6.x
