### ISSUE TITLE
[6.x] Spelltriggering - Missing Scripts

### ISSUE THREAD

**Issue by ghost** [TrinityCore/TrinityCore#14825]
Rev: https://github.com/TrinityCore/TrinityCore/commit/ca9237fbcd134abf91bae354bef60da8ab69cde7
DB: TDB 6.01

Several spells don't have any script for their triggered spell effects:

**ToDo List:**
- [ ] DnD - Spell: www.wowhead.com/spell=43265/death-and-decay not doing any damage.
- [ ] Mirror Images - Cast spell ID : 55342 You see nothing, no copy appears.
- [x] Druid Spell "Moonfire" take no damage that make "Moonfire" quest can't be done.
  Link: [ClassID 11] http://www.wowhead.com/class=11/druid
  [SpellID 164812] http://www.wowhead.com/spell=164812/moonfire
  [QuestID 26948] http://www.wowhead.com/quest=26948/moonfire
- [ ] Stealth [ID: 1784] won't work at all. After clicking the buff appears, but u are actually not stealthed.
- [ ] Shadow Reflection [ID: 152151] won't work properly. It doesn't mimic my abilites .
- [ ] Pet Dk not spawning with spell Raise Dead http://www.wowhead.com/spell=46584/Raise-Dead
- [ ] Core/BFD/Spells Restorative Waters At cast spell 150020 should cast 150022
- [ ] [6.x][Rogue] Core/Spell: Rogue Talent: Burst of Speed
- [x] [master] warrior Charge not working
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/19373673-6-x-death-and-decay-and-probably-more-spells?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource>

**Comment by DDuarte** [comment]
What does "The spellscript is updated." mean?

**Comment by Frytiks** [comment]
I think in spellscript is // updated to 6x         I think if someone updated it it should be tested too ?

**Comment by Frytiks** [comment]
I'm pretty sure, spells with SPELL_AURA_PERIODIC_DAMAGE not do any damage

**Comment by Frytiks** [comment]
When you type into spellwork Death and Decay, i test all spell id's http://prntscr.com/7ly26e 

**All of them doing damage** Only Death Knight spell not

**Comment by BahDumbBugs** [comment]
I wanted to confirm that Moonfire on my Horde Tauren Druid still does not inflict damage on NPCs, Training Dummies, etc. - does the fix in #14853 fix the addressed issues, or is it still outstanding?

**Comment by Shauren** [comment]
Nothing in spellsystem is broken here - many class spells in 6.x trigger damage with a second triggered spell (which is not cast automatically from dbc data), all of them require scripting.

**Comment by Runic-WoW** [comment]
Nothing in spellsystem is broken here - many class spells in 6.x trigger damage with a second triggered spell (which is not cast automatically from dbc data), all of them require scripting.

Correct - To fix moonfire i had to manually edit the spells.dbc file and put the correct data.

**Comment by Rushor** [comment]
> Correct - To fix moonfire i had to manually edit the spells.dbc file and put the correct data.
why not adding a spellscript for it?

**Comment by Rushor** [comment]
suggested fix for "Core/BFD/Spells Restorative Waters At cast spell 150020 should cast 150022"
from https://github.com/TrinityCore/TrinityCore/issues/16938 from @Ulduar

``` CPP
enum Restorative Waters
{
    SPELL_RESTORATIVE_WATERS_DUMMY   = 150020;
};

class spell_gen_restorative_waters : public SpellScriptLoader
{
    public:
        spell_gen_restorative_waters() : SpellScriptLoader("spell_gen_restorative_waters") { }

        class spell_gen_restorative_waters_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_gen_restorative_waters_SpellScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_RESTORATIVE_WATERS_DUMMY))
                    return false;
                return true;
            }
            void HandleDummy(SpellEffIndex /* effIndex */)
            {
               PreventHitDefaultEffect(effIndex);
               GetCaster()->CastSpell(GetCaster(), uint32(GetEffectValue()), true);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_gen_restorative_waters_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_gen_restorative_waters_SpellScript();
        }
};

Maybe you're right, and it was unnecessary. Option number 3:
``` CPP
enum Restorative Waters
{
    SPELL_BATHIEL_RESTORATIVE_WATERS_DUMMY   = 150020;
};

class spell_gen_bathiel_restorative_waters : public SpellScriptLoader
{
    public:
        spell_gen_bathiel_restorative_waters() : SpellScriptLoader("spell_gen_bathiel_restorative_waters") { }

        class spell_gen_bathiel_restorative_waters_SpellScript : public SpellScript
        {
            PrepareSpellScript(spell_gen_bathiel_restorative_waters_SpellScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_RESTORATIVE_WATERS_DUMMY))
                    return false;
                return true;
            }
            void HandleDummy(SpellEffIndex /* effIndex */)
            {
               GetCaster()->CastSpell(GetHitUnit(), uint32(GetEffectValue()), true);
            }

            void Register() override
            {
                OnEffectHitTarget += SpellEffectFn(spell_gen_bathiel_restorative_waters_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
            }
        };

        SpellScript* GetSpellScript() const override
        {
            return new spell_gen_bathiel_restorative_waters_SpellScript();
        }
};
```
``` SQL
-- spell_gen_bathiel_restorative_waters
 DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_gen_bathiel_restorative_waters';
 INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
 (150020,'spell_gen_bathiel_restorative_waters');
```
Need testing.



Although easier through a table spell scripts: D
``` SQL
DELETE FROM `spell_scripts` WHERE `id`=150020;
INSERT INTO `spell_scripts` (`id`,`effIndex`,`delay`,`command`,`datalong`,`datalong2`,`dataint`,`x`,`y`,`z`,`o`) VALUES
(150020,0,0,15,150022,0,0,0,0,0,0);
```

@Ulduar - feel free to open a pr https://github.com/TrinityCore/TrinityCore/pulls for these fixes, so we can remove the issue from this list once it get merged

**Comment by Ulduar** [comment]
@Rushor 
``` CPP
if (!sSpellMgr->GetSpellInfo(SPELL_RESTORATIVE_WATERS_DUMMY))
                    return false;
                return true;
```
SPELL_RESTORATIVE_WATERS_DUMMY need replace on SPELL_BATHIEL_RESTORATIVE_WATERS_DUMMY.

**Comment by djbeauchamp** [comment]
confirmed seal of command in issue in Rev. 9a6c08efa2a5

**Comment by Ulduar** [comment]
``` SQL
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=24 AND `SourceGroup`=0 AND `SourceEntry`=108945;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(24,0,108945,0,0,38,0,30,4,0,28,"","Angelic Bulwark - proc only if Actor health pct below or equal 30 percent."),
(24,0,108945,0,1,114216,0,0,0,0,28,"","Angelic Bulwark - proc only if Actor not have Angelic Bulwark Debuff");

INSERT INTO spell_script_names VALUES 
(108945, "spell_priest_angelic_bulwark");
```
``` CPP
    SPELL_PRIEST_ANGELIC_BULWARK                    = 108945,
    SPELL_PRIEST_ANGELIC_BULWARK_ABSORB             = 114214,
    SPELL_PRIEST_ANGELIC_BULWARK_DEBUFF             = 114216,
// 108945 - Priest Angelic Bulwark Aura.
class spell_priest_angelic_bulwark : public SpellScriptLoader
{
    public:
        spell_priest_angelic_bulwark() : SpellScriptLoader("spell_priest_angelic_bulwark") { }

        class spell_priest_angelic_bulwark_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_priest_angelic_bulwark_AuraScript);

            void OnProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
            {
                PreventDefaultAction();
                int32 basePoints0 = GetTarget()->CountPctFromMaxHealth(aurEff->GetAmount());

                GetTarget()->CastCustomSpell(GetTarget(), SPELL_PRIEST_ANGELIC_BULWARK_ABSORB, &basePoints0, NULL, NULL, true);
                GetTarget()->CastSpell(GetTarget(), SPELL_PRIEST_ANGELIC_BULWARK_DEBUFF, true);
            }

            void Register() OVERRIDE
            {
                OnEffectProc += AuraEffectProcFn(spell_priest_angelic_bulwark_AuraScript::OnProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
            }
        };

        AuraScript* GetAuraScript() const OVERRIDE
        {
            return new spell_priest_angelic_bulwark_AuraScript();
        }
};
```

**Comment by Ulduar** [comment]
@Shauren, @Rushor, cannot find example for full healabsorb amount script hook.
``` CPP
ID - 165102 Вечная тьма
=================================================
Description: Чо'Галл окутывает тьмой случайно выбранного игрока, поглощая все получаемое им исцеление и превращая его в энергию энтропии. 

Когда "Вечная тьма" рассеивается, высвобождается энтропия. Этот эффект восстанавливает всем игрокам здоровье в размере поглощенного исцеления, поровну разделенного между ними.

ToolTip: Поглощение всего получаемого исцеления и превращение его в энергию энтропии.
Category = 0, SpellIconID = 173, activeIconID = 0, SpellVisual = (40709,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x00000004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS)
AttributesEx3: 0x00000100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS)
AttributesEx8: 0x40001000 (SPELL_ATTR8_AURA_SEND_AMOUNT, SPELL_ATTR8_UNK30)
=================================================
MaxAffectedTargets: 3
Spell Level = 103, base 103, max 0

Category = 0
DispelType = 1 (DISPEL_MAGIC)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 16) = 1,50
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x0000002D, AuraIF 0x00480000, ChannelIF 0x00000000
  Ex Target Aura Spell (165102) Вечная тьма
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 301 (SPELL_AURA_SCHOOL_HEAL_ABSORB), value = 0, misc = 127 (127), miscB = 0, periodic = 0
Max Radius (Id 30) 500,00

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 25
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 239 (SPELL_AURA_MOD_SCALE_2), value = 25, misc = 0 (0), miscB = 0, periodic = 0
Max Radius (Id 30) 500,00
```

``` CPP
ID - 165103 Энтропия
=================================================
Description: $@spelldesc165102

ToolTip: Поглощено $w1 ед. исцеления.
Category = 0, SpellIconID = 6228, activeIconID = 0, SpellVisual = (0,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x2D040100 (SPELL_ATTR0_HIDE_IN_COMBAT_LOG, SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE, SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_NEGATIVE_1, SPELL_ATTR0_CASTABLE_WHILE_SITTING, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x000004A8 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_NOT_BREAK_STEALTH, SPELL_ATTR1_CANT_BE_REFLECTED, SPELL_ATTR1_NO_THREAT)
AttributesEx2: 0x10084004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS, SPELL_ATTR2_UNK14, SPELL_ATTR2_NOT_NEED_SHAPESHIFT, SPELL_ATTR2_UNK28)
AttributesEx3: 0x00070000 (SPELL_ATTR3_CANT_TRIGGER_PROC, SPELL_ATTR3_NO_INITIAL_AGGRO, SPELL_ATTR3_IGNORE_HIT_RESULT)
AttributesEx4: 0x00800080 (SPELL_ATTR4_CAN_CAST_WHILE_CASTING, SPELL_ATTR4_UNK23)
AttributesEx5: 0x00060008 (SPELL_ATTR5_USABLE_WHILE_STUNNED, SPELL_ATTR5_USABLE_WHILE_FEARED, SPELL_ATTR5_USABLE_WHILE_CONFUSED)
AttributesEx6: 0x00001000 (SPELL_ATTR6_CASTABLE_WHILE_ON_VEHICLE)
AttributesEx8: 0x00001000 (SPELL_ATTR8_AURA_SEND_AMOUNT)
AttributesEx9: 0x00100000 (SPELL_ATTR9_UNK20)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Stackable up to 999
Cast time (Id 1) = 0,00
Duration: ID (21)  -1, 0, -1
Interrupt Flags: 0x00000000, AuraIF 0x00480000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 0, misc = 0 (0), miscB = 0, periodic = 0
```
Should absorb full heal, on remove by expire cast custom spell.
``` CPP
ID - 165116 Энтропия
=================================================
Description: Накладывает на всех игроков щит, поглощающий урон равный объему выпущенной энергии энтропии. Мощность всех наложенных на игроков щитов равна.

ToolTip: Поглощение $w1 ед. урона.
Category = 0, SpellIconID = 6228, activeIconID = 0, SpellVisual = (40739,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000 [3] 0x00000000

SpellSchoolMask = 32 (SPELL_SCHOOL_MASK_SHADOW)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x2D000000 (SPELL_ATTR0_CASTABLE_WHILE_MOUNTED, SPELL_ATTR0_NEGATIVE_1, SPELL_ATTR0_CASTABLE_WHILE_SITTING, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x000004A8 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_NOT_BREAK_STEALTH, SPELL_ATTR1_CANT_BE_REFLECTED, SPELL_ATTR1_NO_THREAT)
AttributesEx2: 0x10084004 (SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS, SPELL_ATTR2_UNK14, SPELL_ATTR2_NOT_NEED_SHAPESHIFT, SPELL_ATTR2_UNK28)
AttributesEx3: 0x20070100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS, SPELL_ATTR3_CANT_TRIGGER_PROC, SPELL_ATTR3_NO_INITIAL_AGGRO, SPELL_ATTR3_IGNORE_HIT_RESULT, SPELL_ATTR3_NO_DONE_BONUS)
AttributesEx4: 0x00800081 (SPELL_ATTR4_IGNORE_RESISTANCES, SPELL_ATTR4_CAN_CAST_WHILE_CASTING, SPELL_ATTR4_UNK23)
AttributesEx5: 0x00060008 (SPELL_ATTR5_USABLE_WHILE_STUNNED, SPELL_ATTR5_USABLE_WHILE_FEARED, SPELL_ATTR5_USABLE_WHILE_CONFUSED)
AttributesEx6: 0x00001000 (SPELL_ATTR6_CASTABLE_WHILE_ON_VEHICLE)
AttributesEx8: 0x00001000 (SPELL_ATTR8_AURA_SEND_AMOUNT)
AttributesEx9: 0x00100000 (SPELL_ATTR9_UNK20)
=================================================
Spell Level = 0, base 0, max 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRangeNegative = 0, MinRangePositive = 0
    MaxRangeNegative = 0, MaxRangePositive = 0

Cast time (Id 1) = 0,00
Duration: ID (1)  10000, 0, 10000
Interrupt Flags: 0x00000000, AuraIF 0x00480000, ChannelIF 0x00000000
Chance = 0, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA) DIFFICULTY_NONE
BasePoints = 1
Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)
Aura Id 69 (SPELL_AURA_SCHOOL_ABSORB), value = 1, misc = 127 (127), miscB = 0, periodic = 0
Max Radius (Id 30) 500,00
```

``` CPP
// 48743 - Death Pact
/// 6.x
class spell_gen_chogall_infinite_darkness : public SpellScriptLoader
{
    public:
        spell_gen_chogall_infinite_darkness() : SpellScriptLoader("spell_gen_chogall_infinite_darkness") { }

        class spell_gen_chogall_infinite_darkness_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_gen_chogall_infinite_darkness_AuraScript);

            void HandleCalcAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
            {
                if (Unit* caster = GetCaster())
                    int32 RemainingHeal = healAmount;
                    healAmount = int32(caster->CountPctFromMaxHealth(healAmount));
            }
            
            void HandleRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
            {
                AuraRemoveMode removeMode = GetTargetApplication()->GetRemoveMode();
                if (removeMode != AURA_REMOVE_BY_ENEMY_SPELL && removeMode != AURA_REMOVE_BY_EXPIRE)
                    return;

                if (Unit* target = GetTarget())
                {
                    int32 RemainingHeal = healAmount;
                    target->CastCustomSpell(target, 165116, &basepoints, &basepoints, NULL, true, NULL, aurEff);
                }
            }

            void Register() override
            {
                DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_gen_chogall_infinite_darkness_AuraScript::HandleCalcAmount, EFFECT_0, SPELL_AURA_SCHOOL_HEAL_ABSORB);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_gen_chogall_infinite_darkness_AuraScript();
        }
};
```
How will the more correct?

**Comment by Aokromes** [comment]
If anything here is valid, open a PR for it.

**Comment by Ulduar** [comment]
@Aokromes?

**Comment by GnaXi** [comment]
In the latest rev, it seems to be possible to complete the Druid Moonfire quest, even though it still does no damage (only tested as a Night Elf)

**Comment by GnaXi** [comment]
Another spell that doesn't seem to be mentioned is the Warlocks Corruption:
http://www.wowhead.com/spell=172/corruption

It doesn't seem to be doing any damage as of rev. 5da217877be7

**Comment by ArcaneFox** [comment]
Probably this is a hack, but the Stealth is working after this:

```cpp
enum RogueSpells
{
    // ...
    //SPELL_ROGUE_MASTER_OF_SUBTLETY_PERIODIC         = 31666,
    SPELL_ROGUE_MASTER_OF_SUBTLETY_PERIODIC         = 222147,
    // ...
}
```

http://www.wowhead.com/spell=222147/si-7-intel

```
ServerToClient: SMSG_SPELL_START (0x2C3B) Length: 98 ConnIdx: 1
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: SI:7 Intel (222147)
(Cast) SpellXSpellVisualID: 0
(Cast) CastFlags: 11
(Cast) CastTime: 0
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) Ammo.DisplayID: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) CastFlagsEx: 0
(Cast) HitTargetsCount: 0
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) (Target) Flags: Self (0)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(Cast) (Target) Name: 
```

**Comment by ArcaneFox** [comment]
There is no problem with Stealth, the Master of Subtlety isn't working.

```cpp
// 1784 - Stealth
class spell_rog_stealth : public SpellScriptLoader
{
    public:
        spell_rog_stealth() : SpellScriptLoader("spell_rog_stealth") { }

        class spell_rog_stealth_AuraScript : public AuraScript
        {
            PrepareAuraScript(spell_rog_stealth_AuraScript);

            bool Validate(SpellInfo const* /*spellInfo*/) override
            {
                if (!sSpellMgr->GetSpellInfo(SPELL_ROGUE_MASTER_OF_SUBTLETY_PASSIVE) ||
                    !sSpellMgr->GetSpellInfo(SPELL_ROGUE_MASTER_OF_SUBTLETY_DAMAGE_PERCENT) ||
                    !sSpellMgr->GetSpellInfo(SPELL_ROGUE_SANCTUARY) ||
                    !sSpellMgr->GetSpellInfo(SPELL_ROGUE_STEALTH_STEALTH_AURA) ||
                    !sSpellMgr->GetSpellInfo(SPELL_ROGUE_STEALTH_SHAPESHIFT_AURA))
                    return false;
                return true;
            }

            void HandleEffectApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
            {
                Unit* target = GetTarget();

                // Master of Subtlety
                if (AuraEffect const* aurEff = target->GetAuraEffect(SPELL_ROGUE_MASTER_OF_SUBTLETY_PASSIVE, EFFECT_0))
                    target->CastCustomSpell(SPELL_ROGUE_MASTER_OF_SUBTLETY_DAMAGE_PERCENT, SPELLVALUE_BASE_POINT0, aurEff->GetAmount(), target, true);

                target->CastSpell(target, SPELL_ROGUE_SANCTUARY, TRIGGERED_FULL_MASK);
                target->CastSpell(target, SPELL_ROGUE_STEALTH_STEALTH_AURA, TRIGGERED_FULL_MASK);
                target->CastSpell(target, SPELL_ROGUE_STEALTH_SHAPESHIFT_AURA, TRIGGERED_FULL_MASK);
            }

            void HandleEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
            {
                Unit* target = GetTarget();

                // Master of subtlety
                if (target->HasAura(SPELL_ROGUE_MASTER_OF_SUBTLETY_PASSIVE))
                    target->RemoveAurasDueToSpell(SPELL_ROGUE_MASTER_OF_SUBTLETY_DAMAGE_PERCENT);
                    // TODO - MoS 5 sec buff
                    
                target->RemoveAurasDueToSpell(SPELL_ROGUE_STEALTH_STEALTH_AURA);
                target->RemoveAurasDueToSpell(SPELL_ROGUE_STEALTH_SHAPESHIFT_AURA);
            }

            void Register() override
            {
                AfterEffectApply += AuraEffectApplyFn(spell_rog_stealth_AuraScript::HandleEffectApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
                AfterEffectRemove += AuraEffectRemoveFn(spell_rog_stealth_AuraScript::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
            }
        };

        AuraScript* GetAuraScript() const override
        {
            return new spell_rog_stealth_AuraScript();
        }
};
```

**Comment by HannibalRoG** [comment]
I think this report is quite outdated, there are many cases that are already resolved in the master branch.

**Comment by Aokromes** [comment]
well, write fixed ones and i will remove them.

**Comment by HannibalRoG** [comment]
This commits 4b51c78ca18ece6fe1cfb8072514502aae6ba919 resolve this, the class quest are deprecated in 7.1.5.
Druid Spell "Moonfire" take no damage that make "Moonfire" quest can't be done.
Link: [ClassID 11] http://www.wowhead.com/class=11/druid
[SpellID 164812] http://www.wowhead.com/spell=164812/moonfire
[QuestID 26948] http://www.wowhead.com/quest=26948/moonfire

Seal of command is no longer available on legion.
 Spell: http://www.wowhead.com/spell=105361/seal-of-command
When you receive it and activate it, the seal seems to be active when looking at the action bar, but it is not applied to the hero. Seal of Command cannot be deactivated again either, so it is stuck in this non-functional state.

This commit 51207376b7efd06f5a6238ab22663dc9b3cced39 resolve the charge.

Also this link are broken:
http://www.wowhead.com/spell=136494/word-of-glory
http://www.wowhead.com/spell=105361/seal-of-command
 [master] warrior Charge not working

**Comment by Aokromes** [comment]
to much spells on one issue, a lot of things changed, if any is still valid open one issue for each broken spell.
