### ISSUE TITLE
[3.3.5][6.x][DEV] Flame Leviathan - ToDo List

### ISSUE THREAD

**Issue by Rushor** [TrinityCore/TrinityCore#16520]
Branch 3.3.5, rev. 8a0bbc3

**Links to issues concerning** www.wowhead.com/npc=33113/flame-leviathan

- [ ] [3.3.5][6.x][Ulduar] Core/Vehicle - Loot issue https://github.com/TrinityCore/TrinityCore/issues/16233

- [ ] [3.3.5][6.x][Ulduar] Flame Leviathan - Spellcast https://github.com/TrinityCore/TrinityCore/issues/3921

- [ ] [3.3.5][6.x][Ulduar] Core/Creature: Flame Leviathan - Flame Vent stop moving https://github.com/TrinityCore/TrinityCore/issues/15095

- [ ] [3.3.5][6.x][Ulduar] Core/Creature: (Loot)Flame Leviathan Hard Mode https://github.com/TrinityCore/TrinityCore/issues/10568

- [ ] [3.3.5][6.x][Ulduar] Core/Creature: Flame leviathan - Gathering speed https://github.com/TrinityCore/TrinityCore/issues/10567

- [ ] [3.3.5][6.x][Ulduar] Core/Quest: Flame Leviathan must die! https://github.com/TrinityCore/TrinityCore/issues/15204

- [ ] [3.3.5][6.x][Ulduar] Flame Leviathan -Spell Battering Ram not affecting vehicles. https://github.com/TrinityCore/TrinityCore/issues/15185

- [ ] [3.3.5][6.x][Ulduar] Core/Creature - NPCs that are vehicles of other NPCs https://github.com/TrinityCore/TrinityCore/issues/15153

- [ ] [3.3.5][6.x][Ulduar] Core/Vehicles - Problem with Installing Accessories https://github.com/TrinityCore/TrinityCore/issues/15224

- [ ] [3.3.5][6.x][Ulduar] Core/Spell Load Into Catapult and Throw Passenger https://github.com/TrinityCore/TrinityCore/issues/15220

- [ ] [3.3.5][6.x][Ulduar] Core/Creature: Salvaged Chopper - Pick Liquid pyrite https://github.com/TrinityCore/TrinityCore/issues/16157

- [ ] 

- [ ] 

If you find more related issues, link the ticketid here. DO NOT REPORT BUGS IN THIS ISSUE.

**Comment by Killyana** [comment]
I noticed that when you start the hard mode there's extra vehicles that spawns on the same position as the existing ones, I don't know if it's a retail behavior or not.

**Comment by Kittnz** [comment]
The old ones should despawn i think

**Comment by qyh214** [comment]
here is note:
In 0c7655e4ccff854acadd279a1d0f5f87b355c6ad , I can not start this encounter.can someone test?

**Comment by Aokromes** [comment]
i vote you use passive anticheat
