### ISSUE TITLE
[BfA] DB/Creatures: Update creature_template wdb data from 8.0.1 (+locales)

### ISSUE THREAD

**Issue by mdX7** [TrinityCore/TrinityCore#22848]
**Description:**

Bruteforced creature_template data & locales

**Branch(es):**

bfa

**TC rev. hash/commit:** 

947771e6bdbeaa8788c373e0659cd8ca95cd96f2

**Suggested Fix:**
enUS: https://gist.githubusercontent.com/mdX7/1c01df384d37d43e97db067b3dcbb40c/raw/8125d987f3307948e3c311cba10bf14bdfad6f43/28153_enUS_creature_template.sql

Locales
deDE: https://gist.githubusercontent.com/mdX7/4254e2dd3b6c8d4cb116fce72c8d53d3/raw/6a3e2db7827cd0fecfc0b6a829b49c9c4b15468c/28153_deDE_creature_template_locales.sql
esES: https://gist.githubusercontent.com/mdX7/03a01c1a8378df6a3f09f208a01b149e/raw/fd03679e361d054a993b6af719a4987a0855d28c/28153_esES_creature_template_locales.sql
esMX: https://gist.githubusercontent.com/mdX7/129364bcace329b1a149834cde12aec0/raw/177a3ccf4b3bfc2a89c429423b77559caadc178d/28153_esMX_creature_template_locales.sql
frFR: https://gist.githubusercontent.com/mdX7/d85ce43c1cdb2085ce321788b216dc5b/raw/025500cb687c769c662d18c3ff7e0d28fdbacb15/28153_frFR_creature_template_locales.sql
itIT: https://gist.githubusercontent.com/mdX7/b46a224db79255930546769f6991365e/raw/309bf94fca58d2701fbbd8ac9ef6030ea15e8b88/28153_itIT_creature_template_locales.sql
ptBR: https://gist.githubusercontent.com/mdX7/a235420d9ed9d0e74c0a02527c014ba6/raw/cf55618b9e1ee1c5e9f075a92584a016b66e1f07/28153_ptBR_creature_template_locales.sql
koKR: https://gist.githubusercontent.com/mdX7/fc43b10790ad69dcf41320701b83e476/raw/c74768454424f9e97160a68ee22438dfcbbde442/28153_koKR_creature_template_locales.sql
zhCN: https://gist.githubusercontent.com/mdX7/8a454c2bad0477b012e9a7fb275cad60/raw/c92072a05814052ce656c375c9d39659a367485f/28153_zhCN_creature_template_locales.sql
zhTW: https://gist.githubusercontent.com/mdX7/cdd9cf377274787f3976f367bb89e1b8/raw/7f2dbbd98216559f451f52030bf6535cc7934a25/28153_zhTW_creature_template_locales.sql
ruRU: https://gist.githubusercontent.com/mdX7/1770cccabcc98530d928f404afb82034/raw/373a5be83aab07d47ee03f514c29bcb4996c44b0/28153_ruRU_creature_template_locales.sql

**TODO:**
- [ ] Update creature_family datatype to uint16/uint32 done in: https://github.com/TrinityCore/TrinityCore/pull/22831
- [ ] Set primary key of creature_template_model to (CreatureID, Idx) instead of (CreatureID, CreatureDisplayID), Blizzard is using same displayid multiple times @ same creature sometimes..
- [ ] Implement proper displayid loading for the case when sum of probability is = 0 and number of elements > 1 (just pick random element when sum is 0)

**Comment by Traesh** [comment]
@mdX7 
![bd2c2a51ec2aac0ac300a861f0cdd761ceb09c97085ac82e861983fe05ce1909](https://user-images.githubusercontent.com/9392905/49882640-4fc58f00-fe31-11e8-8240-b54d22338b77.jpg)

**Comment by Aokromes** [comment]
superseded by https://github.com/TrinityCore/TrinityCore/issues/23411#issuecomment-502422829
