### ISSUE TITLE
Deprecation details: sha_pass_hash

### ISSUE THREAD

**Issue by Treeston** [TrinityCore/TrinityCore#25157]
# Technical context

The 3.3.5 client uses [SRP6](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) to negotiate client logins. _(See also: [RFC 2945](https://tools.ietf.org/html/rfc2945).)_
This involves the client proving knowledge of `SHA1(salt, SHA1(username, ':', password))` to the server, without the server being able to learn the username, the password, or indeed this hash value.

As a result, it is impossible for a malicious server to learn the client's password when they log in, and impossible for the server to impersonate a client.
This way, even if somebody ends up with a stray backup copy of your accounts database, they couldn't actually _do_ anything with it.

# The issue

As reported in #22913, the current core actually doesn't care about abiding by this property of SRP6. When a user's password is set, the core stores `SHA1(username, ':', password)` to the `sha_pass_hash` column of the `account` table. **This is not information the server should ever store.** When the user next logs on, that value is then used to calculate the `salt` and `verifier` values - the parts that you're **actually** allowed to store.

_(**Side note:** In theory, a user could register, or change their password, without the server ever learning the password, by generating `salt`, calculating an appropriate `verifier`, then sending both to the server. We don't do this, as the 3.3.5 client does not support it, and we have no other trustworthy client software that could fulfill this role.)_

However, over the years – the logic in question hasn't been touched since the early Mangos era – a lot of external applications have cropped up, which use the `sha_pass_hash` field to authenticate users and allow them to change their passwords.

So we don't want to just remove the field from the `account` table without any notice. Thus, this deprecation timeline.
_(Are you a developer impacted by this change? Read further below for how you can correctly authenticate users!)_

# Deprecation timeline

A trio of pull requests were designed to restructure the existing SRP6 implementation from the ground up without impacting backwards compatibility. These have been merged.

* [x] #25093 **General cleanup and refactoring**
* [x] #25131 **Split SRP6 into its own file**
* [x] #25135 **Restructure `account` while keeping backwards compatibility fields**

This means all necessary fields are now in place for forward-compatible secure authentication.
This was followed by official deprecation of `sha_pass_hash` on August 6th.

* [x] #25138 **Deprecate `sha_pass_hash`**

Upon the final deprecation deadline on **September 6th, 2020**, a pull request was be merged, removing `sha_pass_hash` from the `account` table and all associated functionality from the core.

* [x] #25156 **Remove `sha_pass_hash`**

# Proper interfacing with SRP6

The `account` table contains `salt` and `verifier` columns containing the respective SRP6 values.
* `salt` is a cryptographically random 32-byte value
* `verifier` is derived from `salt`, as well as the user's `username` (all uppercase) and their `password` (all uppercase)

If you are registering a user, or changing a user's password, generate a random `salt`, then calculate the appropriate `verifier`, and store both in the database.
If you are logging a user in, re-calculate the `verifier` using the stored `salt` and their login details, and compare it against the stored `verifier`. If the values match, the login details are correct.

To obtain the `verifier`:
* Calculate `h1 = SHA1("USERNAME:PASSWORD")`, substituting the user's username and password converted to uppercase
  * This is the old `sha_pass_hash` value!
* Calculate `h2 = SHA1(salt || h1)`, where `||` is concatenation (the `.` operator in PHP)
  * Note that both `salt` and `h1` are **binary**, not hexadecimal strings!
* Treat `h2` as an integer in little-endian order (the first byte is the least significant)
* Calculate `(g ^ h2) % N`
  * `^` is modular exponentiation, `%` is the modulo operator
  * `g` and `N` are parameters, which are fixed in the WoW implementation:
    * `g = 7`
    * `N = 0x894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7`
* Convert the result back to a byte array in little-endian order
* This is your `verifier` - you're done!

# Example PHP implementations

* _(Make sure the PHP GMP extension is loaded! Uncomment `extension=gmp` in your `php.ini`.)_
* [`CalculateSRP6Verifier.php`](https://gist.github.com/Treeston/db44f23503ae9f1542de31cb8d66781e)
* [`GetSRP6RegistrationData.php`](https://gist.github.com/Treeston/40b99dd71f55d55c68857919088b2e41)
* [`VerifySRP6Login.php`](https://gist.github.com/Treeston/34d9249fb467dddc11b2568e74f8cb1e)

**Comment by calaluis** [comment]
Hello,

I would like to inform that I have just implemented this change described, using the latest version download of this following web application:

https://github.com/TrinityCore/WoWSimpleRegistration

The error it gives, is the following below:

Fatal error: Uncaught Error: Call to undefined function gmp_init() in C:\Site\application\include\functions.php:293 Stack trace: #0 C:\Site\application\application\include\functions.php(325): calculateSRP6Verifier('USERTEST', '12345678', '\x9E6\x9F-Q\x93\xCF\xFA\x06hh\xEE\xC9Z\xDA...') #1 C:\Site\application\application\include\user.php(195): getRegistrationData('USERTEST', '12345678') #2 C:\Site\application\application\include\user.php(32): user::normal_register() #3 C:\Site\application\index.php(34): user::post_handler() #4 {main} thrown in C:\Site\application\application\include\functions.php on line 293

I look forward to your comments, and I look forward to what can be done in the face of this unexpected error.

**Comment by Treeston** [comment]
@calaluis ensure GMP is loaded, uncomment `extension=gmp` in your `php.ini`.

**Comment by calaluis** [comment]
> @calaluis ensure GMP is loaded, uncomment `extension=gmp` in your `php.ini`.

Thank you very much @Treeston  for the help. I was unaware that what I needed was to load a PHP extension (I use version 7.3.13).

Query: Can this implementation be made for C # .NET?

**Comment by Treeston** [comment]
Sure - a quick search suggests that [`System.Numerics.BigInteger`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger) is the system library type to use for bignumber computation.

The reference implementation is only 8 functional lines, so I'd recommend just translating it line-by-line, allowing you to cross-reference intermediate values if necessary.

**Comment by xIvan0ff** [comment]
Possible Python3 Implementation:
https://gist.github.com/xIvan0ff/9e39c07cab8e03e1e51194a4406448ed

Please let me know if any issues are found. Thanks.

**Comment by Treeston** [comment]
@xIvan0ff use [`secrets`](https://docs.python.org/3/library/secrets.html) for crypto, not `random`

Also, you can easily verify that your result is correct - just replace `salt`/`verifier` in your DB and try to log in.

**Comment by xIvan0ff** [comment]
> @xIvan0ff use [`secrets`](https://docs.python.org/3/library/secrets.html) for crypto, not `random`
> 
> Also, you can easily verify that your result is correct - just replace `salt`/`verifier` in your DB and try to log in.

Updated it.

Also I currently don't have a TC database. Will check it out as soon as I do. 👍

**Comment by xIvan0ff** [comment]
@Treeston do you have Discord? Have couple of questions

**Comment by Treeston** [comment]
You can find TC authors on `irc.rizon.net`, `#trinity`.

**Comment by xIvan0ff** [comment]
@Treeston seems like it's down.

**Comment by Aokromes** [comment]
https://github.com/TrinityCore/TrinityCore/commit/bcdbdd6f23ce65cc0e381e61d2840140dce79311

**Comment by MatthDefrenne** [comment]
Someone have an implementation on js, for node js?

**Comment by Treeston** [comment]
A cursory search would suggest [`.getRandomValues()`](https://nodejs.org/api/webcrypto.html#webcrypto_crypto_getrandomvalues_typedarray) for randomness, and [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) for arbitrary-size integers.

As I suggested for the Python implementation,

> The reference implementation is only 8 functional lines, so I'd recommend just translating it line-by-line, allowing you to cross-reference intermediate values if necessary.

**Comment by wsh5237** [comment]
Excuse me,How to implement with java here
![image](https://user-images.githubusercontent.com/16352998/136701818-b3c97d55-a5a0-44af-b3c4-d77a1ccd2f27.png)

**Comment by Treeston** [comment]
While I have never worked with that class, there appears to be a `BigInteger(byte[])` constructor in Java, which takes a big-endian signed binary representation.

Assuming you have the SHA1 hash in a byte array, you would first append a null byte (to force a positive sign), then reverse the array (so the first entry becomes last entry and vice versa).

HTH

**Comment by juandav** [comment]
for nodejs: https://www.npmjs.com/package/@trinity-flux/srp6

**Comment by anyanfei** [comment]
package main

import (
	"bytes"
	"crypto/rand"
	"crypto/sha1"
	"fmt"
	"math/big"
	"strings"
)

/**
这是TrinityCore官方给出的Verifier生成方法，且勿修改这个文本，目前只有C++和php的扩展，我花了很长时间用golang实现了一次，这是唯一一份
To obtain the verifier:
Calculate h1 = SHA1("USERNAME:PASSWORD"), substituting the user's username and password converted to uppercase
This is the old sha_pass_hash value!
Calculate h2 = SHA1(salt || h1), where || is concatenation (the . operator in PHP)
Note that both salt and h1 are binary, not hexadecimal strings!
Treat h2 as an integer in little-endian order (the first byte is the least significant)
Calculate (g ^ h2) % N
^ is modular exponentiation, % is the modulo operator
g and N are parameters, which are fixed in the WoW implementation:
g = 7
N = 0x894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7
Convert the result back to a byte array in little-endian order
This is your verifier - you're done!
*/

var byteSize = 32

func h1Hash(u, p string) []byte {
	rI := fmt.Sprintf("%s:%s", strings.ToUpper(u), strings.ToUpper(p))
	sha := sha1.New()
	sha.Write([]byte(rI))
	return sha.Sum(nil)
}

func h2Hash(salt, h1 string) []byte {
	rI := fmt.Sprintf("%s%s", salt, h1)
	sha := sha1.New()
	sha.Write([]byte(rI))
	return sha.Sum(nil)
}

// BytesToLittleEndian 将bytes转为big.int (little endian)
func bytesToLittleEndian(b []byte) []byte {
	for i := 0; i < len(b)/2; i++ {
		b[i], b[len(b)-i-1] = b[len(b)-i-1], b[i]
	}
	return b
}

func bytesConvertBigIntH2(h2 []byte) *big.Int {
	newB := new(big.Int)
	newB.SetBytes(bytesToLittleEndian(h2))
	return newB
}

// BigIntPowAndMod g^h2 mod N
func (srp *SRP) bigIntPowAndMod(h2 *big.Int) *big.Int {
	bi := new(big.Int)
	bi.Exp(srp.g, h2, srp.N)
	return bi
}

//StrPadByType 0 = "left",1 = "right", 2 = both
func strPadByType(Input string, PadLength int, PadString string, PadType int) string {
	var leftPad, rightPad = 0, 0
	numPadChars := PadLength - len(Input)
	if numPadChars <= 0 {
		return Input
	}
	var buffer bytes.Buffer
	buffer.WriteString(Input)
	switch PadType {
	case 0:
		leftPad = numPadChars
		rightPad = 0
	case 1:
		leftPad = 0
		rightPad = numPadChars
	case 2:
		rightPad = numPadChars / 2
		leftPad = numPadChars - rightPad
	}
	var leftBuffer bytes.Buffer
	/* 左填充：循环添加字符*/
	for i := 0; i < leftPad; i++ {
		leftBuffer.WriteString(PadString)
		if leftBuffer.Len() > leftPad {
			leftBuffer.Truncate(leftPad)
			break
		}
	}
	/* 右填充：循环添加字符串*/
	for i := 0; i < rightPad; i++ {

		buffer.WriteString(PadString)

		if buffer.Len() > PadLength {

			buffer.Truncate(PadLength)

			break

		}
	}
	leftBuffer.WriteString(buffer.String())
	return leftBuffer.String()
}

type SRP struct {
	// large safe prime number
	N *big.Int
	// generator modulo N
	g *big.Int
	// salt bin2 bytes
	saltByte []byte
}

func (srp *SRP) generateSalt() error {
	b := make([]byte, byteSize)
	_, err := rand.Read(b)
	if err != nil {
		return err
	}
	srp.saltByte = b
	return nil
}

func (srp *SRP) getSalt() string {
	return fmt.Sprintf("%s", srp.saltByte)
}

func newSRP() SRP {
	var srp SRP
	srp.N = new(big.Int)
	srp.g = new(big.Int)
	srp.N.SetString("894B645E89E1535BBDAD5B8B290650530801B18EBFBF5E8FAB3C82872A3E9BB7", 16)
	srp.g.SetString("7", 16)
	return srp
}

// CreateVerifier 生成验证者 返回salt盐和验证者
// @params username:账号 password:密码
// @return salt:盐 verifier:验证者 err:错误
func CreateVerifier(username, password string) (salt string, verifier []byte, err error) {
	// 0、初始化g N的SRP6初始值
	auth := newSRP()
	// 1、生成盐
	err = auth.generateSalt()
	if err != nil {
		return "", nil, err
	}
	// 2、获得盐
	salt = auth.getSalt()
	h1 := h1Hash(username, password)
	h2 := h2Hash(salt, string(h1))
	// 3、让h2用小端序
	newH2 := bytesConvertBigIntH2(h2)
	// 4、g^h2 mod N
	expResult := auth.bigIntPowAndMod(newH2)
	b := expResult.Bytes()
	// 5、在末位加0补位
	verifierStr := strPadByType(string(bytesToLittleEndian(b)), 32, "0", 1)
	verifier = []byte(verifierStr)
	return
}

func main() {
	salt, verifier, err := CreateVerifier("anyanfei", "123456789")
	if err != nil {
		return
	}
	fmt.Println(salt, verifier)
}

Implement with go language :-)
